host: 127.0.0.1
spring:
  application:
    name: nacos-config
  # Nacos配置
  cloud:
    nacos:
      config:
        server-addr: ${host}:8848
        file-extension: yaml
  config:
    import: nacos:applicaiton.yaml?refresh=true

# 微信相关
wx:
  # 微信公众平台
  # todo 需替换配置
  mp:
    token: xxx
    aesKey: xxx
    appId: xxx
    secret: xxx
    config-storage:
      http-client-type: HttpClient
      key-prefix: wx
      redis:
        host: 127.0.0.1
        port: 6379
      type: Memory
  # 微信开放平台
  # todo 需替换配置
  open:
    appId: xxx
    appSecret: xxx
# 对象存储
# todo 需替换配置
cos:
  client:
    accessKey: xxx
    secretKey: xxx
    region: xxx
    bucket: xxx
#canal:
#  server: 192.168.11.110:11111  #你canal的地址
#  destination: example
canal.conf:
  canalServerHost: 127.0.0.1:11111
  batchSize: 500
  syncBatchSize: 1000
  retries: 0
  timeout:
  mode: tcp
  consumerProperties:
    # 配置canal 地址 把127.0.0.1换成自己的
    canal.tcp.server.host: 127.0.0.1:11111
    canal.tcp.zookeeper.hosts:
    canal.tcp.batch.size: 500
    canal.tcp.username:
    canal.tcp.password:
  srcDataSources:
    defaultDS:
      url: jdbc:mysql://127.0.0.1:3306/my_db?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true
      username: root
      password: 123456
  canalAdapters:
    - instance: example
      groups:
        - groupId: g1
          outerAdapters:
            - name: logger
            - name: es7                           # or es7
              key: exampleKey
              hosts: http://127.0.0.1:9200                # es 集群地址, 逗号分隔
              properties:
                mode: rest # transport or rest         # 可指定transport模式或者rest模式
                # security.auth: test:123456      # only used for rest mode
                cluster.name: elasticsearch       # es cluster name