server:
  port: 8102
spring:
  # 数据库配置
  # todo 需替换配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/my_db
    username: root
    password: 123456
  # Redis 配置
  # todo 需替换配置
  redis:
    database: 1
    host: localhost
    port: 6379
    timeout: 5000
    password: 123456
  # Elasticsearch 配置
  # todo 需替换配置
  elasticsearch:
    uris: http://localhost:9200
    username: root
    password: 123456

canal.conf:
  canalServerHost: 127.0.0.1:11111
  batchSize: 500
  syncBatchSize: 1000
  retries: 0
  timeout:
  mode: tcp
  srcDataSources:
    defaultDS:
      url: jdbc:mysql://127.0.0.1:3306/my_db?useUnicode=true
      username: root
      password: 123456
  canalAdapters:
    - instance: example
      groups:
        - groupId: g1
          outerAdapters:
            -
              key: exampleKey
              name: es7                           # or es7
              hosts: 127.0.0.1:9200               # es 集群地址, 逗号分隔
              properties:
                mode: rest # transport or rest         # 可指定transport模式或者rest模式
                # security.auth: test:123456      # only used for rest mode
                cluster.name: elasticsearch       # es cluster name